### ISSUE TITLE
Small bug in CSV download for estimated cases on covid19.sanger.ac.uk

### ISSUE THREAD

**Issue by theosanderson** [covince/covince#120]
I haven't chased whether this affects other metrics, or depends on lineage choices, yet:
![image](https://user-images.githubusercontent.com/19732295/148477068-43036c2a-378d-4503-a803-3fb3e7df9972.png)

**Comment by theosanderson** [comment]
(no changes made from default page load)

**Comment by richardgoater** [comment]
thanks for reporting, will take a look
